# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pcaprub"
  s.version = "0.12.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["shadowbq"]
  s.date = "2013-04-22"
  s.description = "libpcap bindings for ruby compat with JRUBY Ruby1.8 Ruby1.9"
  s.email = "shadowbq@gmail.com"
  s.extensions = ["ext/pcaprub/extconf.rb"]
  s.extra_rdoc_files = [
    "FAQ.rdoc",
    "LICENSE",
    "README.rdoc",
    "USAGE.rdoc",
    "ext/pcaprub/pcaprub.c"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "FAQ.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "USAGE.rdoc",
    "examples/dead_cap.rb",
    "examples/file_cap.rb",
    "examples/simple_cap.rb",
    "examples/telnet-raw.pcap",
    "ext/pcaprub/extconf.rb",
    "ext/pcaprub/pcaprub.c",
    "lib/pcaprub.bundle",
    "lib/pcaprub.rb",
    "lib/pcaprub/common.rb",
    "lib/pcaprub/ext.rb",
    "lib/pcaprub/version.rb",
    "pcaprub.gemspec",
    "test/helper.rb",
    "test/test_pcaprub.rb",
    "test/test_pcaprub_unit.rb"
  ]
  s.homepage = "http://github.com/shadowbq/pcaprub"
  s.require_paths = ["lib"]
  s.rubyforge_project = "pcaprub"
  s.rubygems_version = "1.8.24"
  s.summary = "libpcap bindings for ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pcaprub>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<pcaprub>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<pcaprub>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

